### ISSUE TITLE
source and bug report commands

### ISSUE THREAD

**Issue by Sapein** [slowlygoingon/TheBakingBot#1]
There should be a command called `source` (or perhaps just `src`) that just sends a link to this repository. 

Additionally there should be a command (perhaps called `bug` or something) that either links to the Issue Tracker here with some text (perhaps something like:
```Encounter a bug with the bot? Have an idea for something the bot could do? [link to issue tracker here]```.

This would heighten the visibility of the sourcecode of the bot, in addition to allowing others to help contribute by knowing where the source is located.

**Comment by slowlygoingon** [comment]
Thank you for your suggestions! I've added the source command, I will add a bug/issue tracker one too.

**Comment by slowlygoingon** [comment]
All suggestions have been implemented
